### ISSUE TITLE
自己紹介です。

### ISSUE THREAD

**Issue by masa830s** [masa830s/doshisha_test_project#1]
リーダーを拝命した藤川といいます。

**Comment by nomakuchi** [comment]
藤川先生、はじめまして。

**Comment by masa830s** [comment]
profile を編集して写真をアップしてみました。

**Comment by ghost** [comment]
さっそく拝見しました:)

2016-02-11 22:46 GMT+09:00 FUJIKAWA Masahiro notifications@github.com:

**Comment by chikayoshida** [comment]
拝見しました。ありがとうございます。
